### ISSUE TITLE
Toggle WiFi and 3G in Status menu

### ISSUE THREAD

**Issue by justdroid** [saurabh2590/EasyAccess#15]
FEATURE REQUEST
Click on WiFi or 3G status line in Status menu should toggle WiFi or 3G on/off

DETAILS
Users would like to toggle WiFi on/off and 3G on/off directly from the Status menu. Currently, they can only see the current WiFi or 3G status but then need to go via Homscreen 3 > Settings > Android Settings > WiFi > Toogle On, which is much too cumbersome.

LIKELY MODULE
status/StatusApp.java

**Comment by manishoswal** [comment]
Instead of changing WiFi & Mobile Data status (ON/OFF) from Settings, user can change network status inside the app. 
We can change WiFi/3G status from the app for android Froyo to  KitKat. 
For Android Lollipop (5.x) user cannot switch ON/OFF Mobile Data programmatically, 

Please check below links for details.
- [Link 1](http://stackoverflow.com/questions/29340150/android-l-5-x-turn-on-off-mobile-data-programmatically/29340462?noredirect=1#)
- [Link 2](http://stackoverflow.com/questions/26539445/the-setmobiledataenabled-method-is-no-longer-callable-as-of-android-l-and-later)
